# Generated by Django 5.2.16 on 2026-07-25 09:47

import apps.numbering.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OtpRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("phone", apps.numbering.fields.PhoneNumberField(db_index=True)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("LOGIN", "Sign in"),
                            ("VERIFY_PHONE", "Verify phone number"),
                            ("RESET_PIN", "Reset PIN"),
                            ("ENROL_DEVICE", "Enrol a new device"),
                        ],
                        db_index=True,
                        default="LOGIN",
                        max_length=20,
                    ),
                ),
                ("code_hash", models.CharField(max_length=64)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("invalidated_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("delivered", models.BooleanField(default=False)),
                ("delivery_provider", models.CharField(blank=True, max_length=30)),
                ("delivery_message_id", models.CharField(blank=True, max_length=120)),
                ("delivery_error", models.CharField(blank=True, max_length=200)),
                ("delivery_status", models.CharField(blank=True, max_length=30)),
                ("channel", models.CharField(default="sms", max_length=20)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otp_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["phone", "purpose", "-created_at"],
                        name="auth_phone__phone_3fc1ed_idx",
                    )
                ],
            },
        ),
    ]
