# Generated by Django 5.2.16 on 2026-07-25 10:09

import apps.common.fields
import apps.numbering.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Guardian",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=60)),
                ("last_name", models.CharField(max_length=60)),
                ("other_name", models.CharField(blank=True, max_length=60)),
                (
                    "gender",
                    models.CharField(
                        blank=True, choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "phone",
                    apps.numbering.fields.PhoneNumberField(
                        blank=True, default=None, null=True, unique=True
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                ("state_of_origin", models.CharField(blank=True, max_length=40)),
                ("lga", models.CharField(blank=True, max_length=60, verbose_name="LGA")),
                ("photo", models.ImageField(blank=True, null=True, upload_to="people/")),
                ("nin", apps.common.fields.EncryptedTextField(blank=True, default="")),
                ("occupation", models.CharField(blank=True, max_length=80)),
                ("employer", models.CharField(blank=True, max_length=120)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="guardian_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("first_name", models.CharField(max_length=60)),
                ("last_name", models.CharField(max_length=60)),
                ("other_name", models.CharField(blank=True, max_length=60)),
                (
                    "gender",
                    models.CharField(
                        blank=True, choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("phone", apps.numbering.fields.PhoneNumberField(blank=True, default="")),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                ("state_of_origin", models.CharField(blank=True, max_length=40)),
                ("lga", models.CharField(blank=True, max_length=60, verbose_name="LGA")),
                ("photo", models.ImageField(blank=True, null=True, upload_to="people/")),
                ("nin", apps.common.fields.EncryptedTextField(blank=True, default="")),
                ("staff_number", models.CharField(max_length=40, unique=True)),
                (
                    "staff_type",
                    models.CharField(
                        choices=[("TEACHING", "Teaching"), ("NON_TEACHING", "Non-teaching")],
                        default="TEACHING",
                        max_length=14,
                    ),
                ),
                ("designation", models.CharField(blank=True, max_length=80)),
                ("qualification", models.CharField(blank=True, max_length=120)),
                ("date_employed", models.DateField(blank=True, null=True)),
                ("date_exited", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("ON_LEAVE", "On leave"),
                            ("SUSPENDED", "Suspended"),
                            ("EXITED", "Exited"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("bank_name", models.CharField(blank=True, max_length=60)),
                (
                    "bank_account_number",
                    apps.common.fields.EncryptedTextField(blank=True, default=""),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff",
                        to="academics.department",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "staff",
                "ordering": ["last_name", "first_name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("first_name", models.CharField(max_length=60)),
                ("last_name", models.CharField(max_length=60)),
                ("other_name", models.CharField(blank=True, max_length=60)),
                (
                    "gender",
                    models.CharField(
                        blank=True, choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("phone", apps.numbering.fields.PhoneNumberField(blank=True, default="")),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                ("state_of_origin", models.CharField(blank=True, max_length=40)),
                ("lga", models.CharField(blank=True, max_length=60, verbose_name="LGA")),
                ("photo", models.ImageField(blank=True, null=True, upload_to="people/")),
                ("nin", apps.common.fields.EncryptedTextField(blank=True, default="")),
                ("admission_number", models.CharField(max_length=40, unique=True)),
                (
                    "matriculation_number",
                    models.CharField(blank=True, db_index=True, max_length=40),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("APPLICANT", "Applicant"),
                            ("ADMITTED", "Admitted, not yet enrolled"),
                            ("ACTIVE", "Active"),
                            ("GRADUATED", "Graduated"),
                            ("WITHDRAWN", "Withdrawn"),
                            ("SUSPENDED", "Suspended"),
                            ("TRANSFERRED", "Transferred out"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=12,
                    ),
                ),
                ("date_admitted", models.DateField(blank=True, null=True)),
                ("date_left", models.DateField(blank=True, null=True)),
                ("blood_group", models.CharField(blank=True, max_length=5)),
                ("medical_notes", models.TextField(blank=True)),
                ("religion", models.CharField(blank=True, max_length=30)),
                (
                    "current_arm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_students",
                        to="academics.classarm",
                    ),
                ),
                (
                    "current_level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_students",
                        to="academics.classlevel",
                    ),
                ),
                (
                    "programme",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="students",
                        to="academics.programme",
                    ),
                ),
                (
                    "stream",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="students",
                        to="academics.stream",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["last_name", "first_name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=60)),
                ("last_name", models.CharField(max_length=60)),
                ("other_name", models.CharField(blank=True, max_length=60)),
                (
                    "gender",
                    models.CharField(
                        blank=True, choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("phone", apps.numbering.fields.PhoneNumberField(blank=True, default="")),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                ("state_of_origin", models.CharField(blank=True, max_length=40)),
                ("lga", models.CharField(blank=True, max_length=60, verbose_name="LGA")),
                ("photo", models.ImageField(blank=True, null=True, upload_to="people/")),
                ("nin", apps.common.fields.EncryptedTextField(blank=True, default="")),
                ("reference", models.CharField(max_length=30, unique=True)),
                ("previous_school", models.CharField(blank=True, max_length=150)),
                ("guardian_name", models.CharField(blank=True, max_length=120)),
                ("guardian_phone", apps.numbering.fields.PhoneNumberField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("SCREENING", "Under screening"),
                            ("OFFERED", "Offer made"),
                            ("ACCEPTED", "Offer accepted"),
                            ("ENROLLED", "Enrolled"),
                            ("REJECTED", "Rejected"),
                            ("WITHDRAWN", "Withdrawn by applicant"),
                        ],
                        db_index=True,
                        default="SUBMITTED",
                        max_length=12,
                    ),
                ),
                (
                    "screening_score",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                ("screening_notes", models.TextField(blank=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("offered_at", models.DateTimeField(blank=True, null=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("acceptance_fee_paid", models.BooleanField(default=False)),
                (
                    "level_applied",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applications",
                        to="academics.classlevel",
                    ),
                ),
                (
                    "programme_applied",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applications",
                        to="academics.programme",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applications",
                        to="academics.academicsession",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admission_decisions",
                        to="people.staff",
                    ),
                ),
                (
                    "student",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="application",
                        to="people.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=120)),
                ("file", models.FileField(upload_to="student-documents/")),
                ("virus_scanned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="people.student",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploads",
                        to="people.staff",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentGuardian",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("FATHER", "Father"),
                            ("MOTHER", "Mother"),
                            ("GUARDIAN", "Guardian"),
                            ("SIBLING", "Sibling"),
                            ("OTHER", "Other"),
                        ],
                        default="GUARDIAN",
                        max_length=10,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("can_pick_up", models.BooleanField(default=True)),
                (
                    "guardian",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ward_links",
                        to="people.guardian",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guardian_links",
                        to="people.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary"],
            },
        ),
        migrations.AddField(
            model_name="student",
            name="guardians",
            field=models.ManyToManyField(
                related_name="students", through="people.StudentGuardian", to="people.guardian"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(fields=["session", "status"], name="people_appl_session_6dc0d9_idx"),
        ),
        migrations.AddConstraint(
            model_name="studentguardian",
            constraint=models.UniqueConstraint(
                fields=("student", "guardian"), name="unique_student_guardian"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["status", "current_arm"], name="people_stud_status_887915_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["status", "programme"], name="people_stud_status_cb76b9_idx"
            ),
        ),
    ]
