# Generated by Django 5.2.16 on 2026-07-27 14:03

import apps.people.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentdocument",
            name="file",
            field=models.FileField(
                upload_to="student-documents/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["pdf", "jpg", "jpeg", "png", "webp", "heic"]
                    ),
                    apps.people.models.validate_document_size,
                ],
            ),
        ),
    ]
