# Generated by Django 5.2.16 on 2026-07-27 13:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IdempotencyRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=190, unique=True)),
                ("method", models.CharField(max_length=10)),
                ("path", models.CharField(max_length=500)),
                ("request_fingerprint", models.CharField(max_length=64)),
                ("status_code", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("response_body", models.TextField(blank=True)),
                ("content_type", models.CharField(blank=True, max_length=100)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "idempotency record",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
