# Generated by Django 5.2.16 on 2026-07-25 10:59

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0002_initial"),
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentComponent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(help_text="CA1, CA2, EXAM", max_length=20)),
                ("name", models.CharField(max_length=60)),
                (
                    "max_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100.00"),
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_components",
                        to="academics.classlevel",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_components",
                        to="academics.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "code"],
            },
        ),
        migrations.CreateModel(
            name="GradingScale",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=60, unique=True)),
                ("is_default", models.BooleanField(db_index=True, default=False)),
                (
                    "pass_percentage",
                    models.DecimalField(decimal_places=2, default=Decimal("40.00"), max_digits=5),
                ),
                ("uses_grade_points", models.BooleanField(default=False)),
                (
                    "level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grading_scales",
                        to="academics.classlevel",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GradeBand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("letter", models.CharField(max_length=4)),
                ("minimum", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "maximum",
                    models.DecimalField(decimal_places=2, default=Decimal("100.00"), max_digits=5),
                ),
                (
                    "grade_point",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=4),
                ),
                ("remark", models.CharField(blank=True, max_length=40)),
                (
                    "scale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_bands",
                        to="assessment.gradingscale",
                    ),
                ),
            ],
            options={
                "ordering": ["-minimum"],
            },
        ),
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                ("recorded_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="assessment.assessmentcomponent",
                    ),
                ),
                (
                    "entered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scores_entered",
                        to="people.staff",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="academics.subjectregistration",
                    ),
                ),
            ],
            options={
                "ordering": ["component__order"],
            },
        ),
        migrations.CreateModel(
            name="SubjectResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "total_score",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=6),
                ),
                (
                    "max_total",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=6),
                ),
                (
                    "percentage",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=5),
                ),
                ("grade", models.CharField(blank=True, max_length=4)),
                (
                    "grade_point",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=4),
                ),
                ("credit_units", models.PositiveSmallIntegerField(default=0)),
                ("is_pass", models.BooleanField(default=False)),
                ("is_complete", models.BooleanField(default=False)),
                ("position", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("cohort_size", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "class_average",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "class_highest",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "class_lowest",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                ("teacher_remark", models.CharField(blank=True, max_length=60)),
                ("computed_at", models.DateTimeField(auto_now=True)),
                (
                    "registration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="academics.subjectregistration",
                    ),
                ),
            ],
            options={
                "ordering": ["registration__subject__code"],
            },
        ),
        migrations.CreateModel(
            name="TermResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("subjects_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "total_score",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=8),
                ),
                (
                    "max_total",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=8),
                ),
                (
                    "average",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=5),
                ),
                ("credit_units_registered", models.PositiveSmallIntegerField(default=0)),
                ("credit_units_earned", models.PositiveSmallIntegerField(default=0)),
                ("gpa", models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                (
                    "cgpa",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
                ),
                ("position", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("cohort_size", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("days_present", models.PositiveSmallIntegerField(default=0)),
                ("days_total", models.PositiveSmallIntegerField(default=0)),
                ("form_teacher_comment", models.CharField(blank=True, max_length=255)),
                ("head_comment", models.CharField(blank=True, max_length=255)),
                (
                    "promotion_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Not yet decided"),
                            ("PROMOTE", "Promote"),
                            ("REPEAT", "Repeat the class"),
                            ("GRADUATE", "Graduate"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("computed_at", models.DateTimeField(auto_now=True)),
                (
                    "enrolment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="term_results",
                        to="academics.enrolment",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="academics.term",
                    ),
                ),
            ],
            options={
                "ordering": ["-term__session__start_date", "term__index", "position"],
            },
        ),
        migrations.AddIndex(
            model_name="assessmentcomponent",
            index=models.Index(
                fields=["subject", "level", "is_active"], name="assessment__subject_8a6703_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="assessmentcomponent",
            constraint=models.UniqueConstraint(
                fields=("code", "level", "subject"), name="unique_component_per_scope"
            ),
        ),
        migrations.AddConstraint(
            model_name="gradeband",
            constraint=models.UniqueConstraint(
                fields=("scale", "letter"), name="unique_band_per_scale"
            ),
        ),
        migrations.AddIndex(
            model_name="score",
            index=models.Index(fields=["registration"], name="assessment__registr_f58cdb_idx"),
        ),
        migrations.AddConstraint(
            model_name="score",
            constraint=models.UniqueConstraint(
                fields=("registration", "component"), name="unique_score_per_component"
            ),
        ),
        migrations.AddIndex(
            model_name="subjectresult",
            index=models.Index(fields=["grade", "is_pass"], name="assessment__grade_07d2d7_idx"),
        ),
        migrations.AddIndex(
            model_name="termresult",
            index=models.Index(fields=["term", "position"], name="assessment__term_id_fa2388_idx"),
        ),
        migrations.AddConstraint(
            model_name="termresult",
            constraint=models.UniqueConstraint(
                fields=("enrolment", "term"), name="one_result_per_enrolment_per_term"
            ),
        ),
    ]
