# Generated by Django 5.2.16 on 2026-07-25 22:10

from django.db import migrations, models


def blank_references_to_null(apps, schema_editor):
    """Counter payments carry no gateway reference.

    They were stored as "", which under the new unconditional unique
    constraint would make every one of them a duplicate of the next.

    `using=` is not optional here: finance is a tenant-only app, and a
    queryset that goes through the router during a tenant migration finds no
    tenant selected and refuses.
    """
    Payment = apps.get_model("finance", "Payment")
    Payment.objects.using(schema_editor.connection.alias).filter(gateway_reference="").update(
        gateway_reference=None
    )


def null_references_to_blank(apps, schema_editor):
    Payment = apps.get_model("finance", "Payment")
    Payment.objects.using(schema_editor.connection.alias).filter(
        gateway_reference__isnull=True
    ).update(gateway_reference="")


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="payment",
            name="one_payment_per_gateway_reference",
        ),
        migrations.AlterField(
            model_name="payment",
            name="gateway_reference",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.RunPython(blank_references_to_null, null_references_to_blank),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                fields=("gateway", "gateway_reference"), name="one_payment_per_gateway_reference"
            ),
        ),
    ]
