# Generated by Django 5.2.16 on 2026-07-25 10:09

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(help_text="e.g. 2025/2026", max_length=20, unique=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_current", models.BooleanField(db_index=True, default=False)),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="ClassArm",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(help_text="A, B, Gold, Silver", max_length=30)),
                ("capacity", models.PositiveSmallIntegerField(default=40)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["level__order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ClassLevel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=40)),
                ("order", models.PositiveSmallIntegerField(db_index=True)),
                (
                    "is_terminal",
                    models.BooleanField(
                        default=False, help_text="Final year: graduates, not promotes"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=120)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Enrolment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("PROMOTED", "Promoted"),
                            ("REPEATED", "Repeating"),
                            ("GRADUATED", "Graduated"),
                            ("WITHDRAWN", "Withdrawn"),
                            ("TRANSFERRED", "Transferred out"),
                        ],
                        default="ACTIVE",
                        max_length=12,
                    ),
                ),
                ("roll_number", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("promotion_note", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "ordering": ["-session__start_date", "student__last_name"],
            },
        ),
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=120)),
            ],
            options={
                "verbose_name_plural": "faculties",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Programme",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "award",
                    models.CharField(
                        choices=[
                            ("ND", "National Diploma"),
                            ("HND", "Higher National Diploma"),
                            ("NCE", "Nigeria Certificate in Education"),
                            ("BSC", "Bachelor's degree"),
                            ("PGD", "Postgraduate Diploma"),
                            ("OTHER", "Other"),
                        ],
                        default="ND",
                        max_length=10,
                    ),
                ),
                ("duration_years", models.PositiveSmallIntegerField(default=2)),
                ("min_credit_units", models.PositiveSmallIntegerField(default=15)),
                ("max_credit_units", models.PositiveSmallIntegerField(default=24)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(blank=True, max_length=80)),
                ("capacity", models.PositiveSmallIntegerField(default=40)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Stream",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=40)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("title", models.CharField(max_length=120)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("COMPULSORY", "Compulsory / Core"),
                            ("ELECTIVE", "Elective"),
                            ("GENERAL", "General studies"),
                        ],
                        default="COMPULSORY",
                        max_length=12,
                    ),
                ),
                ("credit_units", models.PositiveSmallIntegerField(default=0)),
                ("semester_offered", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="SubjectRegistration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("ADVISER_APPROVED", "Approved by adviser"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("DROPPED", "Dropped"),
                        ],
                        default="APPROVED",
                        max_length=20,
                    ),
                ),
                ("is_carryover", models.BooleanField(default=False)),
                ("adviser_approved_at", models.DateTimeField(blank=True, null=True)),
                ("hod_approved_at", models.DateTimeField(blank=True, null=True)),
                ("dropped_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "ordering": ["subject__code"],
            },
        ),
        migrations.CreateModel(
            name="TeachingAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_lead",
                    models.BooleanField(
                        default=True, help_text="Lead lecturer where a course is shared"
                    ),
                ),
            ],
            options={
                "ordering": ["subject__code"],
            },
        ),
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "index",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ]
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="e.g. First Term, First Semester", max_length=40),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("registration_opens_at", models.DateTimeField(blank=True, null=True)),
                ("registration_closes_at", models.DateTimeField(blank=True, null=True)),
                ("result_entry_opens_at", models.DateTimeField(blank=True, null=True)),
                ("result_entry_closes_at", models.DateTimeField(blank=True, null=True)),
                ("results_published_at", models.DateTimeField(blank=True, null=True)),
                ("is_current", models.BooleanField(db_index=True, default=False)),
            ],
            options={
                "ordering": ["session", "index"],
            },
        ),
        migrations.CreateModel(
            name="TimetableEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "day",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Monday"),
                            (2, "Tuesday"),
                            (3, "Wednesday"),
                            (4, "Thursday"),
                            (5, "Friday"),
                            (6, "Saturday"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
            ],
            options={
                "verbose_name_plural": "timetable entries",
                "ordering": ["day", "start_time"],
            },
        ),
    ]
