# Generated by Django 5.2.16 on 2026-07-25 09:24

import apps.common.fields
import apps.tenants.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=40, unique=True)),
                ("name", models.CharField(max_length=80)),
                ("price_ngn", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("billing_period_days", models.PositiveIntegerField(default=365)),
                ("trial_days", models.PositiveIntegerField(default=30)),
                (
                    "max_students",
                    models.PositiveIntegerField(
                        blank=True, help_text="Null = unlimited", null=True
                    ),
                ),
                ("max_staff", models.PositiveIntegerField(blank=True, null=True)),
                ("max_sms_per_month", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "modules",
                    models.JSONField(
                        blank=True, default=list, help_text="Module keys this plan unlocks"
                    ),
                ),
                ("is_public", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["price_ngn"],
            },
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "schema_name",
                    models.CharField(
                        db_index=True,
                        max_length=63,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-z0-9][a-z0-9_]{0,49}$",
                                "A tenant identifier is lowercase letters, digits and underscores only.",
                            )
                        ],
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "slug",
                    models.SlugField(
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-z0-9](?:[a-z0-9-]{1,48}[a-z0-9])$",
                                "Use 3-50 lowercase letters, digits or hyphens; must not start or end with a hyphen.",
                            )
                        ],
                    ),
                ),
                (
                    "institution_type",
                    models.CharField(
                        choices=[
                            ("SECONDARY", "Secondary school"),
                            ("TERTIARY", "Tertiary institution"),
                        ],
                        default="SECONDARY",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending provisioning"),
                            ("PROVISIONING", "Provisioning"),
                            ("FAILED", "Provisioning failed"),
                            ("TRIAL", "Trial"),
                            ("ACTIVE", "Active"),
                            ("PAST_DUE", "Past due"),
                            ("SUSPENDED", "Suspended"),
                            ("ARCHIVED", "Archived"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("contact_name", models.CharField(blank=True, max_length=120)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("trial_ends_at", models.DateTimeField(blank=True, null=True)),
                ("provisioned_at", models.DateTimeField(blank=True, null=True)),
                ("provisioning_error", models.TextField(blank=True)),
                ("suspended_at", models.DateTimeField(blank=True, null=True)),
                ("suspension_reason", models.TextField(blank=True)),
                ("consented_at", models.DateTimeField(blank=True, null=True)),
                ("consent_version", models.CharField(blank=True, max_length=20)),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tenants.plan",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                ("domain", models.CharField(db_index=True, max_length=253, unique=True)),
                ("is_primary", models.BooleanField(db_index=True, default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_custom", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["domain"],
            },
        ),
        migrations.CreateModel(
            name="TenantConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="branding/")),
                ("primary_color", models.CharField(default="#0B6E4F", max_length=9)),
                ("secondary_color", models.CharField(default="#F2A007", max_length=9)),
                ("report_header", models.CharField(blank=True, max_length=255)),
                ("motto", models.CharField(blank=True, max_length=255)),
                ("address", models.TextField(blank=True)),
                ("enabled_modules", models.JSONField(blank=True, default=list)),
                (
                    "label_overrides",
                    models.JSONField(blank=True, default=apps.tenants.models.default_labels),
                ),
                (
                    "sms_sender_id",
                    models.CharField(
                        blank=True, help_text="Registered alphanumeric", max_length=11
                    ),
                ),
                ("sms_backend", models.CharField(blank=True, max_length=100)),
                ("sms_credentials", apps.common.fields.EncryptedTextField(blank=True, default="")),
                ("paystack_public_key", models.CharField(blank=True, max_length=120)),
                (
                    "paystack_secret_key",
                    apps.common.fields.EncryptedTextField(blank=True, default=""),
                ),
                ("flutterwave_public_key", models.CharField(blank=True, max_length=120)),
                (
                    "flutterwave_secret_key",
                    apps.common.fields.EncryptedTextField(blank=True, default=""),
                ),
                ("require_nin", models.BooleanField(default=False)),
                ("globally_unique_phone", models.BooleanField(default=False)),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuration",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(fields=["status", "slug"], name="tenants_ten_status_361aff_idx"),
        ),
    ]
