# Generated by Django 5.2.16 on 2026-07-27 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenantconfiguration",
            name="globally_unique_phone",
        ),
    ]
