# Generated by Django 5.2.16 on 2026-07-25 09:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MobileNumberAllocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ndc", models.CharField(db_index=True, max_length=6, unique=True)),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            ("MTN", "MTN"),
                            ("GLO", "Globacom"),
                            ("AIRTEL", "Airtel"),
                            ("EMTS", "9mobile (EMTS)"),
                            ("NTEL", "ntel"),
                            ("SMILE", "Smile"),
                            ("OTHER", "Other / historic"),
                        ],
                        default="OTHER",
                        max_length=10,
                    ),
                ),
                ("nsn_length", models.PositiveSmallIntegerField(default=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ASSIGNED", "Assigned"),
                            ("WITHDRAWN", "Withdrawn"),
                            ("RESERVED", "Reserved"),
                            ("AVAILABLE", "Available"),
                        ],
                        default="ASSIGNED",
                        max_length=12,
                    ),
                ),
                ("allows_user_accounts", models.BooleanField(default=True)),
                ("source_url", models.URLField(blank=True)),
                ("last_verified_at", models.DateField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "verbose_name": "mobile number allocation",
                "ordering": ["ndc"],
            },
        ),
    ]
