# Generated by Django 5.2.16 on 2026-07-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("numbering", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mobilenumberallocation",
            name="operator",
            field=models.CharField(
                choices=[
                    ("MTN", "MTN"),
                    ("GLO", "Globacom"),
                    ("AIRTEL", "Airtel"),
                    ("EMTS", "9mobile (EMTS)"),
                    ("MAFAB", "Mafab (Mcom)"),
                    ("MTEL", "M-Tel"),
                    ("SMILE", "Smile"),
                    ("VAS_SNS", "VAS / SNS licensees (shared)"),
                    ("OTHER", "Other / historic"),
                ],
                default="OTHER",
                max_length=10,
            ),
        ),
    ]
