# Generated by Django 5.2.16 on 2026-07-25 10:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0002_initial"),
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BiometricDevice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=40, unique=True)),
                ("name", models.CharField(blank=True, max_length=80)),
                ("location", models.CharField(blank=True, max_length=80)),
                ("secret", models.CharField(max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BiometricEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_id", models.CharField(db_index=True, max_length=64)),
                ("occurred_at", models.DateTimeField()),
                (
                    "direction",
                    models.CharField(
                        choices=[("IN", "In"), ("OUT", "Out")], default="IN", max_length=4
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("match_error", models.CharField(blank=True, max_length=120)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="attendance.biometricdevice",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("device", "external_id", "occurred_at"),
                        name="unique_biometric_punch",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StaffAttendance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(db_index=True)),
                ("check_in", models.DateTimeField(blank=True, null=True)),
                ("check_out", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESENT", "Present"),
                            ("ABSENT", "Absent"),
                            ("LATE", "Late"),
                            ("EXCUSED", "Excused"),
                        ],
                        default="PRESENT",
                        max_length=8,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Marked by hand"),
                            ("QR", "QR scan"),
                            ("BIOMETRIC", "Biometric device"),
                            ("IMPORT", "Bulk import"),
                        ],
                        default="MANUAL",
                        max_length=10,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance",
                        to="people.staff",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("staff", "date"), name="unique_staff_attendance_per_day"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StudentAttendance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESENT", "Present"),
                            ("ABSENT", "Absent"),
                            ("LATE", "Late"),
                            ("EXCUSED", "Excused"),
                        ],
                        default="PRESENT",
                        max_length=8,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Marked by hand"),
                            ("QR", "QR scan"),
                            ("BIOMETRIC", "Biometric device"),
                            ("IMPORT", "Bulk import"),
                        ],
                        default="MANUAL",
                        max_length=10,
                    ),
                ),
                ("marked_at", models.DateTimeField(auto_now_add=True)),
                ("note", models.CharField(blank=True, max_length=200)),
                ("version", models.PositiveIntegerField(default=1)),
                ("recorded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "class_arm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance",
                        to="academics.classarm",
                    ),
                ),
                (
                    "marked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_marked",
                        to="people.staff",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance",
                        to="people.student",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance",
                        to="academics.subject",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_attendance",
                        to="academics.term",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "student__last_name"],
                "indexes": [
                    models.Index(
                        fields=["term", "date", "class_arm"], name="attendance__term_id_659c82_idx"
                    ),
                    models.Index(fields=["student", "term"], name="attendance__student_a102f3_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "date", "subject"),
                        name="unique_student_attendance_per_period",
                    )
                ],
            },
        ),
    ]
