# Generated by Django 5.2.16 on 2026-07-25 09:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("actor_label", models.CharField(blank=True, max_length=120)),
                ("action", models.CharField(db_index=True, max_length=60)),
                ("object_type", models.CharField(blank=True, db_index=True, max_length=60)),
                ("object_id", models.CharField(blank=True, db_index=True, max_length=64)),
                ("summary", models.CharField(blank=True, max_length=255)),
                ("before", models.JSONField(blank=True, null=True)),
                ("after", models.JSONField(blank=True, null=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("device_id", models.CharField(blank=True, max_length=128)),
                ("tenant_slug", models.CharField(blank=True, db_index=True, max_length=50)),
                ("succeeded", models.BooleanField(default=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["action", "-created_at"], name="audit_audit_action_0c6a84_idx"
                    ),
                    models.Index(
                        fields=["object_type", "object_id"], name="audit_audit_object__1f9df3_idx"
                    ),
                ],
            },
        ),
    ]
